---
- name: Upgrade and Reboot RHEL & Debian family Linux distros
  hosts: all
  tasks:
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
       yum:
         name: '*'
         state: latest
      when: ansible_os_family == "RedHat"
