---
- name: Upgrade and Reboot RHEL & Debian family Linux distros
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: cambio de usuario a root
      command: sudo su - root
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
      yum:
         name: '*'
         state: latest
      when: ansible_os_family == "RedHat"
